export const CAT_POPULAR_LIST = "CAT_POPULAR_LIST";
export const CAT_POPULAR_LIST_CACHE_KEY = "CAT_POPULAR_LIST_CACHE_KEY"
export const CAT_POPULAR_LIST_TAG = "CAT_POPULAR_LIST_TAG"
export const CAT_POPULAR_LIST_TTL = 5 * 60 * 1000 // 5 minutes
export const CAT_POPULAR_LIST_RETRIES = 2
export const CAT_POPULAR_LIST_RETRY_DELAY = 500 // 0.5 second
