export const BRAND_ALL_LIST_BY_CATEGORIES_ID = "BRAND_ALL_LIST_BY_CATEGORIES_ID";
export const BRAND_ALL_LIST_BY_CATEGORIES_ID_CACHE_KEY =
  "BRAND_ALL_LIST_BY_CATEGORIES_ID_CACHE_KEY";
export const BRAND_ALL_LIST_BY_CATEGORIES_ID_TAG = "BRAND_ALL_LIST_BY_CATEGORIES_ID_TAG";
export const BRAND_ALL_LIST_BY_CATEGORIES_ID_TTL = 5 * 60 * 1000;
export const BRAND_ALL_LIST_BY_CATEGORIES_ID_RETRIES = 2;
export const BRAND_ALL_LIST_BY_CATEGORIES_ID_RETRY_DELAY = 500;
