export const BRAND_POPULAR_LIST = "BRAND_POPULAR_LIST";
export const BRAND_POPULAR_LIST_CACHE_KEY = "BRAND_POPULAR_LIST_CACHE_KEY";
export const BRAND_POPULAR_LIST_TAG = "BRAND_POPULAR_LIST_TAG";
export const BRAND_POPULAR_LIST_TTL = 5 * 60 * 1000;
export const BRAND_POPULAR_LIST_RETRIES = 2;
export const BRAND_POPULAR_LIST_RETRY_DELAY = 500;
