export const IMAGE_RESULT_LIMIT = 12;
export const PRO_SEARCH_IMAGE_LIST = "PRO_SEARCH_IMAGE_LIST";
export const PRO_SEARCH_IMAGE_LIST_CACHE_KEY = "PRO_SEARCH_IMAGE_LIST_CACHE_KEY";
export const PRO_SEARCH_IMAGE_LIST_TAG = "PRO_SEARCH_IMAGE_LIST_TAG";
export const PRO_SEARCH_IMAGE_LIST_TTL = 5 * 60 * 1000; // 5 minutes
export const PRO_SEARCH_IMAGE_LIST_RETRIES = 2;
export const PRO_SEARCH_IMAGE_LIST_RETRY_DELAY = 500; // 0.5 second
