export const PRO_POPULAR_LIST = "PRO_POPULAR_LIST";
export const PRO_POPULAR_LIST_CACHE_KEY = "PRO_POPULAR_LIST_CACHE_KEY";
export const PRO_POPULAR_LIST_TAG = "PRO_POPULAR_LIST_TAG";
export const PRO_POPULAR_LIST_TTL = 5 * 60 * 1000; // 5 minutes
export const PRO_POPULAR_LIST_RETRIES = 2;
export const PRO_POPULAR_LIST_RETRY_DELAY = 500; // 0.5 second
