export const PRO_SUGGESTION_LIST = "PRO_SUGGESTION_LIST";
export const PRO_SUGGESTION_LIST_CACHE_KEY = "PRO_SUGGESTION_LIST_CACHE_KEY";
export const PRO_SUGGESTION_LIST_TAG = "PRO_SUGGESTION_LIST_TAG";
export const PRO_SUGGESTION_LIST_TTL = 5 * 60 * 1000; // 5 minutes
export const PRO_SUGGESTION_LIST_RETRIES = 2;
export const PRO_SUGGESTION_LIST_RETRY_DELAY = 500; // 0.5 second
