export const VOUCHER_DETAIL_PRODUCTS = "VOUCHER_DETAIL_PRODUCTS_KEY";
export const VOUCHER_DETAIL_PRODUCTS_CACHE_KEY = "VOUCHER_DETAIL_PRODUCTS_CACHE_KEY";
export const VOUCHER_DETAIL_PRODUCTS_TAG = "VOUCHER_DETAIL_PRODUCTS_TAG";
export const VOUCHER_DETAIL_PRODUCTS_TTL = 5 * 60 * 1000; // 5 minutes
export const VOUCHER_DETAIL_PRODUCTS_RETRIES = 2;
export const VOUCHER_DETAIL_PRODUCTS_RETRY_DELAY = 500; // 0.5 second
