export const SHOPPING_CART = "SHOPPING_CART";
export const SHOPPING_CART_CACHE_KEY = "SHOPPING_CART_CACHE_KEY";
export const SHOPPING_CART_TAG = "SHOPPING_CART_TAG";
export const SHOPPING_CART_TTL = 5 * 60 * 1000; // 5 minutes
export const SHOPPING_CART_RETRIES = 2;
export const SHOPPING_CART_RETRY_DELAY = 500; // 0.5 second
