export const PRO_TOPPICKS_LIST = "PRO_TOPPICKS_LIST";
export const PRO_TOPPICKS_LIST_CACHE_KEY = "PRO_TOPPICKS_LIST_CACHE_KEY";
export const PRO_TOPPICKS_LIST_TAG = "PRO_TOPPICKS_LIST_TAG";
export const PRO_TOPPICKS_LIST_TTL = 5 * 60 * 1000; // 5 minutes
export const PRO_TOPPICKS_LIST_RETRIES = 2;
export const PRO_TOPPICKS_LIST_RETRY_DELAY = 500; // 0.5 second
